debug: true
contextTimeout: 10000

server:
  port: '8081'
  host: '127.0.0.1'
  env: 'local'
  useRedis: false

services:

database:
  driver: 'postgres'
  mongo:
    host: '127.0.0.1'
    port: '27017'
    username: 'mongo'
    password: 'mongo'
    name: 'mongo'
    sslmode: 'disable'
    timezone: 'Asia/Ho_Chi_Minh'
  postgres:
#    host: '34.92.104.68'
    host: '192.168.1.235'
    port: '5432'
    username: 'postgres'
    password: 'postgres'
    name: 'n_product_service'
    sslmode: 'disable'
    timezone: 'Asia/Ho_Chi_Minh'

jwt:
  secret: 'hgG6T23XD25N'
  accessTokenExpiresIn: 3600
  refreshTokenExpiresIn: 86400
  kid: 'kid'
  aud: 'aud'
  iss: 'iss'
logger:
  level: 'debug'
  enabled: true